export const countryCodes = [
    { code: '+964', name: 'العراق (Iraq)' },
    { code: '+966', name: 'السعودية (Saudi Arabia)' },
    { code: '+971', name: 'الإمارات (UAE)' },
    { code: '+20', name: 'مصر (Egypt)' },
    { code: '+962', name: 'الأردن (Jordan)' },
    { code: '+963', name: 'سوريا (Syria)' },
    { code: '+961', name: 'لبنان (Lebanon)' },
    { code: '+970', name: 'فلسطين (Palestine)' },
    { code: '+967', name: 'اليمن (Yemen)' },
    { code: '+968', name: 'عمان (Oman)' },
    { code: '+965', name: 'الكويت (Kuwait)' },
    { code: '+974', name: 'قطر (Qatar)' },
    { code: '+973', name: 'البحرين (Bahrain)' },
    { code: '+212', name: 'المغرب (Morocco)' },
    { code: '+213', name: 'الجزائر (Algeria)' },
    { code: '+216', name: 'تونس (Tunisia)' },
    { code: '+218', name: 'ليبيا (Libya)' },
    { code: '+249', name: 'السودان (Sudan)' },
    { code: '+222', name: 'موريتانيا (Mauritania)' },
    { code: '+253', name: 'جيبوتي (Djibouti)' },
    { code: '+252', name: 'الصومال (Somalia)' },
    { code: '+269', name: 'جزر القمر (Comoros)' },
    { code: '+1', name: 'الولايات المتحدة وكندا (USA & Canada)' },
    { code: '+44', name: 'بريطانيا (UK)' },
    { code: '+49', name: 'ألمانيا (Germany)' },
    { code: '+33', name: 'فرنسا (France)' },
    { code: '+39', name: 'إيطاليا (Italy)' },
    { code: '+34', name: 'إسبانيا (Spain)' },
    { code: '+7', name: 'روسيا (Russia)' },
    { code: '+86', name: 'الصين (China)' },
    { code: '+91', name: 'الهند (India)' },
    { code: '+81', name: 'اليابان (Japan)' },
    { code: '+82', name: 'كوريا الجنوبية (South Korea)' },
    { code: '+90', name: 'تركيا (Turkey)' },
    { code: '+98', name: 'إيران (Iran)' },
    { code: '+92', name: 'باكستان (Pakistan)' },
    { code: '+62', name: 'إندونيسيا (Indonesia)' },
    { code: '+60', name: 'ماليزيا (Malaysia)' },
    { code: '+55', name: 'البرازيل (Brazil)' },
    { code: '+52', name: 'المكسيك (Mexico)' },
    { code: '+54', name: 'الأرجنتين (Argentina)' },
    { code: '+57', name: 'كولومبيا (Colombia)' },
    { code: '+61', name: 'أستراليا (Australia)' },
    { code: '+64', name: 'نيوزيلندا (New Zealand)' },
    { code: '+27', name: 'جنوب أفريقيا (South Africa)' },
    { code: '+234', name: 'نيجيريا (Nigeria)' },
    { code: '+254', name: 'كينيا (Kenya)' },
  ];
